services:
  - type: web
    name: tg-ai-image-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_token_here
      - key: OPENAI_API_KEY
        value: your_openai_key_here
