services:
  - type: web
    name: telegram-ai-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: <твой_токен_бота>
      - key: OPENAI_API_KEY
        value: <твой_ключ_OpenAI>
      - key: WEBHOOK_URL
        value: https://<имя-приложения>.onrender.com
